# LEVELS
# 0: No prior experience/background in the field is required; the target audience is very broad
# 1: Discerning reader who wants to delve deeper into the L-0 post
# 2: An audience with the necessary background to understand technical and advanced details

[chsh]
title = "Play Therapy with Quantum Mechanics"
tags = ["quantum physics", "game theory"]
[chsh.entry.0]
date = 2026-06-29
level = 0
[chsh.entry.1]
date = 2026-09-01
level = 1

[p-np]
title = "Is it possible to effectively earn $1 million?"
tags = ["mathematics", "complexity theory"]
[p-np.entry.0]
date = 2026-07-01
level = 0

[cat-state]
title = "The Smallest Cat in the Universe"
tags = ["quantum physics", "quantum information", "QEC"]
[cat-state.entry.2]
date = 2026-07-20
level = 2